기본 저장 타입인 Tensor는 Numpy와 유사한 기능을 제공한다.

https://pytorch.org/docs/stable/generated/torch.tensor.html

https://pytorch.org/docs/stable/tensors.html


In [2]:
import numpy as np
import torch

In [3]:
# 리스트로부터 텐서를 만들수 있다.

t1 = torch.tensor([[1,2],[3,4]])

In [4]:
type(t1)

torch.Tensor

In [9]:
t1.dtype #타입 확인

torch.int64

In [10]:
# 타입 지정 가능

t2 = torch.tensor([[1,2],[3,4]], dtype=torch.float64)

In [11]:
t2.dtype

torch.float64

pytorch는 device에 대해 신경써줘야 함


In [15]:
t1.device   #gpu 런타임 실행이나, 텐서는 cpu에 타입으로 저장

device(type='cpu')

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))

Tesla K80


In [17]:
device

device(type='cuda')

In [22]:
t3 = torch.tensor([[1,2],[3,4]], device = 'cuda')  #device 지정

In [19]:
t3.device

device(type='cuda', index=0)

In [20]:
t4 = torch.tensor([[1,2],[3,4]], device = 'cuda:0')

In [21]:
t4.device

device(type='cuda', index=0)

Numpy로 변환 시 gpu device의 tensor는 cpu로 이동 후 변환

In [24]:
t4.numpy()  # gpu device로 설정된 텐서를 numpy로 변환시 에러가 발생

TypeError: ignored

In [26]:
t4.to('cpu').numpy()  # cpu 변환 후 numpy로 변환

array([[1, 2],
       [3, 4]])

tensor의 인덱싱 및 연산은 numpy와 거의 동일

In [28]:
t4[:,1]

tensor([2, 4], device='cuda:0')

In [29]:
t3 + t4

tensor([[2, 4],
        [6, 8]], device='cuda:0')

In [31]:
t1+t4   # t1이 cpu인 경우 gpu의 t4와 연산 안됨, 동일한 device로 맞춰줘야 함

RuntimeError: ignored

In [32]:
t1+t4.to('cpu')

tensor([[2, 4],
        [6, 8]])

데이터 병합 시 torch.cat() 사용

numpy의 reshape은 view() 사용

In [33]:
t5=torch.tensor([[1,2],[3,4]])
t6=torch.tensor([[10,20,30],[30,40,50]])

In [34]:
t5

tensor([[1, 2],
        [3, 4]])

In [36]:
t6

tensor([[10, 20, 30],
        [30, 40, 50]])

In [41]:
t6.size()

torch.Size([2, 3])

In [37]:
t6.t()

tensor([[10, 30],
        [20, 40],
        [30, 50]])

In [39]:
torch.cat([t5,t6], dim=1)

tensor([[ 1,  2, 10, 20, 30],
        [ 3,  4, 30, 40, 50]])

In [43]:
t7=torch.cat([t5,t6.t()], dim=0)

In [44]:
t7

tensor([[ 1,  2],
        [ 3,  4],
        [10, 30],
        [20, 40],
        [30, 50]])

In [48]:
t7.view(1,-1)  #-1은 자동 개수

tensor([[ 1,  2,  3,  4, 10, 30, 20, 40, 30, 50]])

In [49]:
t7.view(2,5)

tensor([[ 1,  2,  3,  4, 10],
        [30, 20, 40, 30, 50]])