# Numpy Basic
* numpy의 array는 list와 유사하나 특화 기능이 조금 다릅니다. 
* numpy 배열과 list는 쉽게 변환 가능합니다
* 리스트는 문자, 숫자, 리스트 등 다양한 요소를 넣을 수 있으나, numpy array는 한가지 데이터 타입만 저장 가능합니다

* numpy array는 list와 달리 배열이 바로 연산 가능합니다

리스트 사용 예시

In [1]:
# 리스트 사용으로 각 항목에 100을 더하는 경우
num = [1,3,4,8,-1]

num_100=[]
for i in num:
  num_100.append(i+100)
print(num_100)

[101, 103, 104, 108, 99]




*   list comprehension
*   리스트를 간단히 만들 수 있습니다. 



In [2]:
# 리스트에서 각각의 요소에 100을 더하는 경우
num = [1,3,4,8,-1]
num_100 = [i+100 for i in num] #list comprehension
print(num_100)

[101, 103, 104, 108, 99]


Numpy 사용시

* np.array()를 통해 리스트를 numpy array로 바꿀 수 있습니다

In [3]:
# numpy array 연산
import numpy as np
num = [1,3,4,8,-1]
num_arr = np.array(num) # 리스트를 numpy array로 변경
num_100 = num_arr + 100
print(num_100)

[101 103 104 108  99]


In [4]:
type(num_arr)

numpy.ndarray

##### array 연산
* 배열끼리의 연산이 되므로 코딩이 매우 간결해집니다

In [5]:
# 리스트에 18, 19년 1,2,3,4분기 매출이 저장되어 있어
# 얼마나 늘었는지 보려고 합니다

year_18 = [100,200,210, 300]
year_19 = [110,220,300, 350]

# 리스트는 같은 위치끼리 연산이 안되므로
rev_diff = [] 
for i in range(4):
    diff = year_19[i] - year_18[i]
    rev_diff.append(diff)
    
print(rev_diff)

[10, 20, 90, 50]


In [6]:
# numpy 활용
year_18 = [100,200,210, 300]
year_19 = [110,220,300, 350]

# 리스트는 같은 위치끼리 연산이 안되므로
year_18_np = np.array(year_18)
year_19_np = np.array(year_19)
rev_diff = year_19_np-year_18_np
print(rev_diff)

[10 20 90 50]


##### 2차 배열(행렬) 만들기
* numpy는 행렬 연산이 가능합니다

In [7]:
# 리스트 2차 배열 형태로 만들기
data_2d = [[1,2,3], [4,5,6], [7,8,9]]
print(data_2d)
print(data_2d[0])
print(data_2d[0][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
2


In [8]:
# numpy 2d array로 변경
data_2d_arr = np.array(data_2d)
print(data_2d_arr)
print(data_2d_arr[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


##### 행렬 연산
* 2d array도 연산이 가능합니다

In [9]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
print(arr1)
print(arr2)
print(arr2-arr1)
print(arr2*arr1)
print(arr2/arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  8 15]
 [24 35 48]
 [63 80 99]]
[[3.         2.         1.66666667]
 [1.5        1.4        1.33333333]
 [1.28571429 1.25       1.22222222]]


* 행렬 연산도 가능합니다
* 행렬 곱은 @ 또는 np.dot()을 사용하면 됩니다

In [10]:
arr1 @ arr2

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [11]:
np.dot(arr1, arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [12]:
# transpose (전치행렬)
# 행렬을 바꿈
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

* np.linspace()는 범위를 입력 개수로 등간격으로 나누어줍니다
* 그래프를 그릴 때 유용합니다

In [14]:
np.linspace(1,3, num=100)

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494