Tensor의 기본 구조를 알아봅시다

https://www.tensorflow.org/guide/tensor

전체적으로는 Numpy와 유사

In [1]:
import tensorflow as tf

In [2]:
# 변수에 값과 배열을 넣어봅시다
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
# numpy 변환
b=a.numpy()

In [4]:
type(b)

numpy.int32

사칙연산 및 행렬곱 등도 쉽게 가능함

In [5]:
arr = tf.constant([[1,2], [3,4]])

In [6]:
arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
arr+3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [8]:
arr*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>

In [9]:
arr2 = tf.constant([[3,4], [5,6]])

In [10]:
arr+arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10]], dtype=int32)>

In [11]:
arr*arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  8],
       [15, 24]], dtype=int32)>

In [12]:
arr@arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 16],
       [29, 36]], dtype=int32)>

In [13]:
tf.argmax(arr)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

Indexing도 Numpy와 동일함

In [14]:
arr3 = tf.constant([1,2,3,4,5])

In [15]:
arr3[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [16]:
arr3[:3].numpy()

array([1, 2, 3], dtype=int32)

In [17]:
arr4 = tf.constant([[1,2,3,4,5],[2,3,4,5,6]])

In [18]:
arr4

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int32)>

In [19]:
arr4[0].numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [20]:
tf.reshape(arr4, [5,2])

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [21]:
arr3.dtype

tf.int32

In [22]:
arr4 = tf.cast(arr4, dtype = tf.float16)

In [23]:
arr4.dtype

tf.float16

tf.variable을 통해 변수를 만들수도 있습니다.

https://www.tensorflow.org/guide/variable

In [24]:
a = tf.Variable([2.0, 3.0])

In [25]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [26]:
a.assign_add([1,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

In [27]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

tensor는 정수와 실수형이 연산되지 않습니다.
 
tf.cast()를 통해서 타입을 맞춰주어야 합니다. 

In [28]:
n1 =tf.constant(10)
n2 = tf.constant(5.)

In [30]:
n1+n2   #타입이 맞지 않아서 오류가 발생합니다

InvalidArgumentError: ignored

In [31]:
n1 = tf.cast(n1, tf.float32)

In [32]:
n1+n2

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>